HEADER:
  label: "About me"

PRESENTATION:
  description: |
    I am a data scientist and software engineer with a passion for harnessing the power of artificial intelligence to solve complex problems and create impactful solutions. My expertise spans building predictive models, developing scalable AI-driven applications, and transitioning legacy systems to modern architectures. With a strong foundation in Python, machine learning, and cloud technologies like Google Cloud Platform (GCP), I enjoy designing innovative tools that optimize workflows and enhance decision-making.
    
    What excites me most is the intersection of AI and software engineering, where I can merge creativity with technical excellence. Whether it’s crafting efficient algorithms, designing intelligent diagnostic tools, or implementing robust software systems, I am driven by a desire to push technological boundaries and deliver meaningful outcomes. Currently based in Bangalore, I am always eager to collaborate on projects that challenge conventional thinking and bring transformative ideas to life.
    
DOING:
  enabled: true
  label: "What I'm doing"
  items:
    - title: "Generative AI"
      icon: "config/assets/icons/ai.svg"
      description: "Professional development of Gen AI applications"
    - title: "Scripting"
      icon: "config/assets/icons/code.svg"
      description: "Automation and task scripting using Python to enhance efficiency and productivity."
    - title: "Machine Learning"
      icon: "config/assets/icons/compass.svg"
      description: "Intuitive and visually appealing user interfaces and user experiences."
    - title: "Web Development"
      icon: "config/assets/icons/laptop-code.svg"
      description: "High-quality development of sites at the professional level."

SKILLS:
  enabled: true
  label: "Soft Skills"
  items:
    - title: "Fast Learner"
      icon: "config/assets/icons/bolt.svg"
      description: "I have the ability to quickly acquire new knowledge and adapt to changing technological environments."
    - title: "Teamwork"
      icon: "config/assets/icons/user.svg"
      description: "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."
    - title: "Problem Solving"
      icon: "config/assets/icons/gear.svg"
      description: "I am creative and efficient in identifying and solving technical problems."
    - title: "Effective Communication"
      icon: "config/assets/icons/comment.svg"
      description: "I have the skill to convey ideas clearly and concisely, both technically and non-technically."

TECHNOLOGIES:
  enabled: true
  label: "Tech Experience"
  items:
    - title: "Python"
      icon: "config/assets/icons/python.svg"
    - title: "AI"
      icon: "config/assets/icons/ai.svg"
    - title: "Pandas"
      icon: "config/assets/icons/pandas.svg"
    - title: "HTML"
      icon: "config/assets/icons/html.svg"
    - title: "Jupyter"
      icon: "config/assets/icons/jupyter.svg"
