HEADER:
  label: "Awards"

POSTS:
  - title: "Star Award"
    category: "Prodapt"
    published: "2024-01-31"
    image: "config/assets/posts/star_of_the_month_jan_2024.jpeg"
    pdf: "config/assets/posts/Star_of_the_Month_Award__81265051.pdf"
    

  - title: "Star Award"
    category: "Prodapt"
    published: "2024-09-25"
    image: "config/assets/posts/star_of_the_month_sep_2024.jpeg"
    pdf: "config/assets/posts/Star_of_the_Month_Award__72480261.pdf"
    

  - title: "Spotlight Award"
    category: "Prodapt"
    published: "2023-12-22"
    image: "config/assets/posts/spotlight_award_dec_2023.jpeg"
    pdf: "config/assets/posts/Spotlight_Award__48042655.pdf"
    

  
