# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Senior Software Engineer"
  name: "Govardhan Selvaraj"
  username: "govardhan26" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/IMG_3059.png"

INFO:
  - label: "Email"
    value: "govardhan_selvaraj@yahoo.com"
    icon: "mail-outline"
  - label: "Phone"
    value: "+91 9025817537"
    icon: "phone-portrait-outline"
  - label: "Birthday"
    value: "February 26, 1998"
    icon: "calendar-outline"
  - label: "Location"
    value: "Bengaluru, Karnataka, India"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/in/govardhan-selvaraj"
  - icon: "logo-github"
    url: "https://github.com/govardhan26"
  - icon: "code-outline"
    url: "https://www.hackerrank.com/profile/govardhan_selva1"
  - icon: "logo-ionic"
    url: "https://www.kaggle.com/gova26"
  
