HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2013 — 2015"
      institution: "Indian School Certificate"
      degree: "Mathematics & Biology"
      description: "Completed coursework in computer science and digital media, with a particular focus on web development and programming. Collaborated on projects involving coding and design integration."
    - period: "2015 — 2018"
      institution: "Dr.Grd College of Arts & Science, Coimbatore"
      degree: "Bachelors of Commerce in Actuarial Management"
      description: "Studied fine arts with a focus on sculpture and advanced painting techniques. Took part in workshops and intensive studio sessions, receiving feedback from industry professionals."
    - period: "2018 — 2020"
      institution: "Bharathiar University, Coimbatore"
      degree: "Masters in Data Science"
      description: "Pursued a Bachelor of Fine Arts degree, specializing in interactive media and digital design. Graduated with a portfolio of projects blending traditional art forms with emerging technologies."

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "Dec 2019 — May 2020"
      position: "Data Science Intern"
      description: "Data science intern at data tale"
    - period: "Jun 2020 — Jul 2021"
      position: "Junior Data Scientist"
      description: "Worked on the design and development of websites for small to medium-sized businesses. Collaborated closely with developers to ensure responsive and user-friendly designs. Led the redesign of the company’s website, improving user engagement by 25%."
    - period: "Aug 2021 — Dec 2022"
      position: "Data Analyst"
      description: "Led a team of designers to create visually stunning campaigns for major clients in the advertising industry. Managed the creative direction of print and digital media, ensuring consistent branding and high-quality designs. Oversaw the production of advertisements that won industry awards."
    - period: "Dec 2022 — Present"
      position: "Senior Software Engineer"
      description: "Direct and oversee the creative process for a range of projects, from concept to execution. Lead cross-functional teams to create innovative design solutions for branding, marketing, and digital experiences. Recently led the redesign of a global brand’s digital presence, increasing online sales by 40%."

LANGUAGES:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "English"
      proficiency: "100%"
    - language: "Tamil"
      proficiency: "100%"
    - language: "Hindi"
      proficiency: "60%"
    - language: "Malayalam"
      proficiency: "60%"

SKILLS:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "Data Science"
      proficiency: "80%"
    - skill: "MLOps"
      proficiency: "80%"
    - skill: "Machine Learning"
      proficiency: "90%"
    - skill: "Data Analysis"
      proficiency: "90%"
    - skill: "Python Programming"
      proficiency: "90%"
    - skill: "Generative AI"
      proficiency: "70%"
    - skill: "Natural Language Processing"
      proficiency: "80%"
    - skill: "Image Processing"
      proficiency: "60%"
    - skill: "Web Design"
      proficiency: "80%"
    - skill: "Ajile Project Management"
      proficiency: "70%"
    - skill: "Product Designing"
      proficiency: "40%"
    - skill: "WebScraping"
      proficiency: "100%"
